using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

[RequireComponent(typeof(NavMeshAgent))]
public class WayPointPatrol : MonoBehaviour
{
    public NavMeshAgent navMeshAgent;
    public Transform[] waypoints;
    private int currentWaypointIndex;
    void Start()
    {
        navMeshAgent= GetComponent<NavMeshAgent>();
        navMeshAgent.SetDestination(waypoints[0].position);
    }
    void Update()
    {
        if (navMeshAgent.remainingDistance<navMeshAgent.stoppingDistance)
        {
            currentWaypointIndex= (currentWaypointIndex +1)%waypoints.Length;
            navMeshAgent.SetDestination(waypoints[currentWaypointIndex].position);
        }
    }
}
